services:
  mysql:
    container_name: mysql_container
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ../Data/mysql:/var/lib/mysql
    restart: unless-stopped